services:
  webdiagtools:
    #build:
    #  context: .
    #  network: host
    image: pbeyl/webdiagtools:latest
    ports: [] # disable port mapping
    environment:
      BIND_HOST: 127.0.0.1
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./data:/app/data
    network_mode: host
    restart: always
    container_name: webdiagtools

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - webdiagtools
    network_mode: host
    restart: always
    ports: [] # disable port mapping when using host networking
    environment:
      APP_HOST: ${APP_HOST}
      UPSTREAM: 127.0.0.1:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./static:/srv/static:ro
      - ./logs:/var/log/caddy

volumes:
  caddy_data:
  caddy_config: