services:
  net-tools-app:
    build: 
      context: .
      network: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    volumes:
      - ./data:/app/data
    restart: always
    container_name: net-tools

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - net-tools-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      APP_HOST: ${APP_HOST}
      UPSTREAM: net-tools-app:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - ./static:/srv/static:ro
      - ./logs:/var/log/caddy

volumes:
  caddy_data:
  caddy_config: